
mode: immediate


branchName: '${issue.number}-${issue.title}'

# Label-based prefixes
branches:
  - label: hotfix
    prefix: hotfix/
  - label: [library, release]
    prefix: library/
  - label: [process, release]
    prefix: release/

openPR: true


copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueMilestoneToPR: true
copyIssueProjectsToPR: true

prSkipCI: true
