mode: immediate

# Branch name piece after the prefix → "8-my-feature"
branchName: '${issue.number}-${issue.title}'

# Label-based prefixes (matches your templates)
branches:
  - label: hotfix
    prefix: hotfix/
  - label: [library, release]
    prefix: library/
  - label: [process, release]
    prefix: release/

# Open PRs as DRAFT by default; we’ll "ready" hotfix via API in the workflow
openPR: true

# Copy stuff from Issue → PR
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueMilestoneToPR: true
# optional:
# copyIssueProjectsToPR: true

# Avoid CI on the initial empty commit
prSkipCI: true
