name: Release - Process
description: Creates CR for a Process
title: "<short description of change>"
labels:
  - release
  - process

body:
  - type: input
    id: user_email
    attributes:
      label: Requester email
      description: Email of the user whom the CR will be assigned to.
      placeholder: "email@noreply.com"
    validations:
      required: true


  - type: input
    id: backup_contact
    attributes:
      label: Backup contact (email)(required for CR approval)
      placeholder: "email@noreply.com"


  - type: input
    id: target_end_date
    attributes:
      label: Target end date
      description: "When will this be completed/deployed? Use MM-DD-YY."
      placeholder: "MM-DD-YY"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Overview
        Provide context for reviewers to understand the change.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Put as much detail as possible about the change.
      placeholder: >
        Describe the change in detail. Paste any neccessary info/technical details.
    validations:
      required: true

  - type: input
    id: business_value
    attributes:
      label: Business value (executive summary)
      description: "Business-speak version of the update: benefits, outcomes, KPIs, etc."
      placeholder: "How does the DMV benefit from this change in laymans' terms."
    validations:
      required: true

  - type: input
    id: implementation_plan
    attributes:
      label: Implementation plan
      placeholder: "Explain the implementation plan, providing details."
    validations:
      required: true

  - type: input
    id: backout_plan
    attributes:
      label: Backout plan
      placeholder: "How to revert the change if needed."
    validations:
      required: true

  - type: input
    id: validation_plan
    attributes:
      label: Validation plan
      placeholder: "Pre/post checks, success criteria, monitoring, etc."
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        ## Audience & Contacts
        _Who is impacted and how they were told._

  - type: input
    id: impacted_groups
    attributes:
      label: Impacted groups
      placeholder: "Group name(s)"
    validations:
      required: true

  - type: input
    id: impacted_users_emails
    attributes:
      label: Impacted users (emails)
      placeholder: "email@noreply.com"
    validations:
      required: true

  - type: input
    id: last_notified_when
    attributes:
      label: When were impacted users last notified?
      placeholder: "MM/DD/YY"
    validations:
      required: true

  - type: dropdown
    id: last_notified_how
    attributes:
      label: How were impacted users last notified?
      options:
        - Meeting
        - Teams message
        - Email
        - Call
        - In Person
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Effort/Project
      options:
        - Defect Resolution
        - Executive Sponsor Projects
        - Maintenance and Operation
        - Legislative Mandate
        - User Request
        - Test Environment
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Confirmations
      description: Please check any that apply.
      options:
        - label: Impacts the public.
          required: false
        - label: Involves CDT.
          required: false
        - label: New app (ESD needs to know).
          required: false
        - label: Impact a Vendors.
          required: false
